### ISSUE TITLE
[QUESTION] How do I pass the authentication to other controllers.

### ISSUE THREAD

**Issue by davidbuckleyni** [cornflourblue/aspnet-core-3-jwt-refresh-tokens-api#1]
Thanks for this example I am trying to implement as you didn't show another controller can you tell me how I consume it taking into account that the user is already authenticated.

**Comment by davidbuckleyni** [comment]
Its fine sorted it thanks for an amazin tutorial

**Comment by daniol** [comment]
Same question here. 
I want to access to the current "User" in other controller.
How did you sorted it out, @davidbuckleyni ?
